## YAML Template.
RDS_DB_NAME: 'travelx'
RDS_USERNAME: 'postgres'
RDS_PASSWORD: 'utomedia@236L'
RDS_HOSTNAME: 'localhost'
RDS_PORT: '5432'
ASSET_HOST: 'localhost:3000'
SITE_URL: 'http://localhost:3000'